modLoader="javafml"
loaderVersion="[28,)"

[[mods]]
modId="dark_nether"
version="1.0.0"
displayName="Dark Nether"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="enzoj, MCreator"

[[dependencies.dark_nether]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.14.4]"
    ordering="NONE"
    side="BOTH"



